"""
Check if finite wreath products are k-generated.
"""

from cayleylab.groups.wreath import WreathProduct
from cayleylab.core.bfs import build_ball
from itertools import combinations
from collections import deque
import time
import sys

def check_k_generation(group_spec, k=2, max_check=None):
    # group_spec: string like "Z/2 x Z/2 wr Z/3"
    # k: size of generating sets to test (default 2 for pairs)
    # max_check: limit on how many subsets to check (None = check all)
   
    print(f" Checking {k}-generation for {group_spec}")
    
    # Set up the group with its default generators
    group = WreathProduct() # create a wreath product group instance (not yet configured)
    configured = group.parse_options({"spec": group_spec}) 
    gens = configured.default_generators() # get gens like [t, T, a, b]
    
    # Step 1: Enumerate all elements
    # Use existing build_ball to find all elements starting from identity
    # radius=50 is way bigger than needed but ensures we get everything
    V, _, _, _, _ = build_ball(configured, gens, radius=50) #builds what were checking our subsets against
    print(f"\nGroup has {len(V)} elements")
    
    # Step 2: Build word dictionary
    # For each element, store a word (sequence of generators) that produces it
    # This lets us later "replay" the word to use the element as a generator
    # Example: element (1, ((1, (1,0)),)) gets word "ta"
    identity = configured.identity()
    elem_to_word = {identity: ""}  # Dictionary: element -> word
    queue = deque([identity])      # BFS queue
    
    while queue:
        state = queue.popleft()
        for g in gens:
            new = g.apply(state)
            if new not in elem_to_word:  # If new element discovered
                elem_to_word[new] = elem_to_word[state] + g.name  # Record word
                queue.append(new)
    
    elements = list(elem_to_word.keys())
    non_id = [e for e in elements if e != identity]  # All except identity
    
    # Step 3: Calculate total k-subsets to check
    from math import comb
    total = comb(len(non_id), k)  # e.g. C(191, 2) = 18,145
    print(f"Testing C({len(non_id)}, {k}) = {total} subsets")
    if max_check:
        print(f"(checking first {max_check} only)\n")
    else:
        print()
    
    def make_gen(word):
        # Turn a word like "ta" into a generator object
        # This is needed because build_ball expects generators with apply() method
        # but our elements are just tuples (data, not functions)
        class WordGen:
            def __init__(self):
                self.name = word or "e"
                self.gens = {g.name: g for g in gens}  # Store actual generators
            def apply(self, s):
                # Apply the word letter by letter: "ta" means apply t, then a
                for c in word:
                    s = self.gens[c].apply(s)
                return s
        return WordGen()
    
    # Step 4: Main loop - check all k-subsets
    count = 0           # How many generating subsets found
    checked = 0         # How many subsets checked
    examples = []       # Store some example generating sets
    start = time.time()
    
    for subset in combinations(non_id, k):  # Loop through all k-subsets
        checked += 1
        if max_check and checked > max_check:
            break
        
        # Turn each element in subset into a "generator" by wrapping its word
        subset_gens = [make_gen(elem_to_word[e]) for e in subset]
        
        # Use YOUR build_ball to compute the subgroup generated by this subset
        V_sub, _, _, _, _ = build_ball(configured, subset_gens, radius=50)
        
        # Check if this subset generates the whole group
        if len(V_sub) == len(elements):
            count += 1  # Found a generating subset!
            if len(examples) < 10:
                examples.append(tuple(elem_to_word[e] for e in subset))
        
        # Progress update every 500 subsets
        if checked % 500 == 0:
            elapsed = time.time() - start
            print(f"  {checked}/{min(total, max_check or total)}, found {count} ({elapsed:.1f}s)")
    
    # Step 5: Calculate results
    elapsed = time.time() - start
    prob = count / checked if checked > 0 else 0  # Probability p_k(G)
    print()
    print(f"  Group: {group_spec}")
    print(f"  |G| = {len(elements)}")
    print(f"  Checked: {checked} out of {total}")
    print(f"  Generating: {count}")
    print(f"  p_{k}(G) = {prob:.6f}")
    print(f"  Time: {elapsed:.1f}s")

    
    if count > 0:
        print(f"\n IS {k}-GENERATED")
        print("\nExamples:")
        for words in examples:
            s = ", ".join(w or "e" for w in words)
            print(f"  {{{s}}}")
    else:
        print(f"\n NOT {k}-GENERATED")
    
    print()
    return {'is_k_gen': count > 0, 'prob': prob, 'count': count}


if __name__ == "__main__":
    # Command-line argument handling
    
    if len(sys.argv) > 1 and sys.argv[1] in ['-h', '--help']:
        print("Usage: python prob_genSet.py [group] [--k K] [--max N]")
        print("\nExamples:")
        print("  python prob_genSet.py 'Z/2 wr Z/3' --k 2")
        print("  python prob_genSet.py 'Z/2 x Z/2 wr Z/3' --k 3 --max 5000")
        sys.exit()
    
    # Default values
    spec = "Z/2 x Z/2 wr Z/3"  # Default group to check
    k = 2                      # Default: check 2-generation
    max_check = None           # Default: check all subsets
    
    # Parse command-line arguments
    if len(sys.argv) > 1:
        spec = sys.argv[1]
    if len(sys.argv) > 2 and sys.argv[2] == "--k":
        k = int(sys.argv[3])
    if len(sys.argv) > 4 and sys.argv[4] == "--max":
        max_check = int(sys.argv[5])
    
    # Run the check
    check_k_generation(spec, k=k, max_check=max_check)


